/*
CREATE TABLE HomeQuotes (
  QuoteID CHAR(5) PRIMARY KEY DEFAULT '0',
  DateQuoted DATE NOT NULL,
  QuoteExpired DATE NOT NULL,
  BasePremium DECIMAL(8,2),
  Tax DECIMAL(6,2),
  Total DECIMAL(9,2)
);
*/
CREATE TABLE HomeQuote_Seq (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DELIMITER $$
CREATE TRIGGER T_HomeQuotes_Insert
BEFORE INSERT ON HomeQuotes
FOR EACH ROW
BEGIN
  INSERT INTO HomeQuote_Seq VALUES (NULL);
  SET NEW.QuoteID= CONCAT('H', LPAD(LAST_INSERT_ID(), 4, '0'));
END$$
DELIMITER ;


/*
CREATE TABLE VehicleQuotes (
  QuoteID CHAR(5) PRIMARY KEY DEFAULT '0',
  DateQuoted DATE NOT NULL,
  QuoteExpired DATE NOT NULL,
  BasePremium DECIMAL(8,2) NOT NULL,
  Tax DECIMAL(6,2) NOT NULL,
  Total DECIMAL(9,2) NOT NULL
);
*/

CREATE TABLE VehicleQuotes_Seq(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DELIMITER $$
CREATE TRIGGER T_VehicleQuotes_Insert
BEFORE INSERT ON VehicleQuotes
FOR EACH ROW
BEGIN
  INSERT INTO VehicleQuotes_Seq VALUES (NULL);
  SET NEW.QuoteID= CONCAT('V', LPAD(LAST_INSERT_ID(), 4, '0'));
END$$
DELIMITER ;


