/*
CREATE TABLE HomeQuotes (
  QuoteID CHAR(6) PRIMARY KEY DEFAULT '0',
  DateQuoted DATE NOT NULL,
  QuoteExpired DATE NOT NULL,
  BasePremium DECIMAL(8,2),
  Tax DECIMAL(6,2),
  Total DECIMAL(9,2)
);
*/
CREATE TABLE HomeQuote_Seq (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DELIMITER $$
CREATE TRIGGER T_HomeQuotes_Insert
BEFORE INSERT ON HomeQuotes
FOR EACH ROW
BEGIN
  INSERT INTO HomeQuote_Seq VALUES (NULL);
  SET NEW.QuoteID= CONCAT('HQ', LPAD(LAST_INSERT_ID(), 4, '0'));
END$$
DELIMITER ;

/*
CREATE TABLE HomePolicy (
  PolicyID CHAR(6) PRIMARY KEY,
  UserID INT NOT NULL,
  HomeID DECIMAL(5) NOT NULL,
  QuoteID CHAR(6) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  BasePremium DECIMAL(7,2),
  Tax DECIMAL(4,2) NOT NULL,
  Total DECIMAL(7,2) NOT NULL,
  FOREIGN KEY (UserID) REFERENCES HomeOwner(UserID),
  FOREIGN KEY (QuoteID) REFERENCES HomeQuotes(QuoteID),
  FOREIGN KEY (HomeID) REFERENCES Home(HomeID)
);
*/
CREATE TABLE HomePolicy_Seq (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DELIMITER $$
CREATE TRIGGER T_HomePolicy_Insert
BEFORE INSERT ON HomeQuotes
FOR EACH ROW
BEGIN
  INSERT INTO Homepolicy_Seq VALUES (NULL);
  SET NEW.QuoteID= CONCAT('HP', LPAD(LAST_INSERT_ID(), 4, '0'));
END$$
DELIMITER ;

/*
CREATE TABLE VehicleQuotes (
  QuoteID CHAR(6) PRIMARY KEY DEFAULT '0',
  DateQuoted DATE NOT NULL,
  QuoteExpired DATE NOT NULL,
  BasePremium DECIMAL(8,2) NOT NULL,
  Tax DECIMAL(6,2) NOT NULL,
  Total DECIMAL(9,2) NOT NULL
);
*/

CREATE TABLE VehicleQuotes_Seq(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DELIMITER $$
CREATE TRIGGER T_VehicleQuotes_Insert
BEFORE INSERT ON VehicleQuotes
FOR EACH ROW
BEGIN
  INSERT INTO VehicleQuotes_Seq VALUES (NULL);
  SET NEW.QuoteID= CONCAT('VQ', LPAD(LAST_INSERT_ID(), 4, '0'));
END$$
DELIMITER ;




/*
CREATE TABLE VehiclePolicy (
  PolicyID CHAR(6) PRIMARY KEY,
  VehicleID DECIMAL(5) NOT NULL,
  UserID INT NOT NULL,
  QuoteID CHAR(6) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  BasePremium DECIMAL(6,2) NOT NULL,
  Tax DECIMAL(4,2) NOT NULL,
  Total DECIMAL(7,2) NOT NULL,
  ReplacementCostValue DECIMAL(6,2) NOT NULL,
  FOREIGN KEY (UserID) REFERENCES PrincipleDriver(UserID),
  FOREIGN KEY (QuoteID) REFERENCES VehicleQuotes(QuoteID),
  FOREIGN KEY (VehicleID) REFERENCES Vehicle(VehicleID)
);
*/

CREATE TABLE VehiclePolicy_Seq(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DELIMITER $$
CREATE TRIGGER T_VehiclePolicy_Insert
BEFORE INSERT ON VehiclePolicy
FOR EACH ROW
BEGIN
  INSERT INTO VehiclePolicy_Seq VALUES (NULL);
  SET NEW.PolicyID= CONCAT('VP', LPAD(LAST_INSERT_ID(), 4, '0'));
END$$
DELIMITER ;


